export const mockTrendingNFTs = [
  {
    id: 1,
    name: "The Pond",
    collection: "POND",
    image: "https://i.seadn.io/gcs/files/12345abcde.png",
    floorPrice: 0.25,
    volume24h: 15.3,
    likes: 1200,
    chain: "Base",
  },
  {
    id: 2,
    name: "Cyber Koi",
    collection: "KOI",
    image: "ipfs://QmQoi12345abcde/cyberkoi.png",
    floorPrice: 0.18,
    volume24h: 9.8,
    likes: 860,
    chain: "Ethereum",
  },
  {
    id: 3,
    name: "MetaFrogs",
    collection: "FROGZ",
    image: "https://i.seadn.io/gae/_frogs_art_123.png",
    floorPrice: 0.4,
    volume24h: 20.1,
    likes: 1430,
    chain: "Polygon",
  },
  {
    id: 4,
    name: "Celestial Whales",
    collection: "WHALE",
    image: "ipfs://QmWhale12345abcd/celestial-whale.png",
    floorPrice: 1.1,
    volume24h: 43.2,
    likes: 2240,
    chain: "Ethereum",
  },
  {
    id: 5,
    name: "ApeVortex",
    collection: "APEVX",
    image: "https://i.seadn.io/gcs/files/ape_vortex.png",
    floorPrice: 0.75,
    volume24h: 31.4,
    likes: 1900,
    chain: "Base",
  },
  {
    id: 6,
    name: "Nebula Cats",
    collection: "NEBULACAT",
    image: "ipfs://QmNebulaCatsImg123/nebula-cat.png",
    floorPrice: 0.09,
    volume24h: 5.4,
    likes: 720,
    chain: "Arbitrum",
  },
  {
    id: 7,
    name: "Pixel Nomads",
    collection: "NOMAD",
    image: "https://i.seadn.io/gcs/files/pixel_nomad.png",
    floorPrice: 0.15,
    volume24h: 8.7,
    likes: 930,
    chain: "Optimism",
  },
  {
    id: 8,
    name: "Void Samurai",
    collection: "VOID",
    image: "ipfs://QmVoid123samurai/image.png",
    floorPrice: 0.6,
    volume24h: 28.9,
    likes: 1740,
    chain: "Polygon",
  },
  {
    id: 9,
    name: "Berachain Monkeys",
    collection: "BERAMONK",
    image: "https://i.seadn.io/gcs/files/bera_monkey_01.png",
    floorPrice: 0.22,
    volume24h: 12.5,
    likes: 880,
    chain: "Berachain",
  },
  {
    id: 10,
    name: "DreamScapes",
    collection: "DRMSC",
    image: "ipfs://QmDream12345scape/dreamscape.png",
    floorPrice: 1.8,
    volume24h: 54.6,
    likes: 3200,
    chain: "Ethereum",
  },
];
